# Generated by Django 6.0.2 on 2026-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='Assignment_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='techerregist',
            name='employeeID',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
