# Generated by Django 6.0.2 on 2026-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='report_sent',
            field=models.BooleanField(default=False),
        ),
    ]
