# Generated by Django 6.0.2 on 2026-02-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0005_rename_report_sent_assignment_result_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
