# Generated by Django 6.0.2 on 2026-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0006_blacklistedrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
