# Generated by Django 6.0.2 on 2026-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_teacher',
        ),
        migrations.AddField(
            model_name='message',
            name='is_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
