# Generated by Django 6.0.2 on 2026-02-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_room'),
        ('student_app', '0002_remove_student_department_studentassignmentattempt_and_more'),
        ('teacher_app', '0007_assignment_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adminMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.techerregist')),
                ('members', models.ManyToManyField(related_name='chat_room', to='student_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Group_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('is_sender', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group_room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
