# Generated by Django 6.0.2 on 2026-03-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_room_group_message'),
        ('student_app', '0002_remove_student_department_studentassignmentattempt_and_more'),
        ('teacher_app', '0007_assignment_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_room',
            name='adminMember',
        ),
        migrations.AddField(
            model_name='group_room',
            name='admin_student',
            field=models.ManyToManyField(blank=True, related_name='admin_in_student_rooms', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='group_room',
            name='admin_teacher',
            field=models.ManyToManyField(blank=True, related_name='admin_in_student_rooms', to='teacher_app.techerregist'),
        ),
        migrations.AddField(
            model_name='group_room',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='teacher_app.techerregist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_room',
            name='teacher_members',
            field=models.ManyToManyField(blank=True, related_name='teacher_chat_rooms', to='teacher_app.techerregist'),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mssg', to='chat.group_room'),
        ),
        migrations.AlterField(
            model_name='group_room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='student_chat_rooms', to='student_app.student'),
        ),
    ]
