# Generated by Django 6.0.2 on 2026-03-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_group_room_adminmember_and_more'),
        ('student_app', '0002_remove_student_department_studentassignmentattempt_and_more'),
        ('teacher_app', '0007_assignment_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_room',
            name='admin_student',
        ),
        migrations.RemoveField(
            model_name='group_room',
            name='admin_teacher',
        ),
        migrations.RemoveField(
            model_name='group_room',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group_room',
            name='teacher_members',
        ),
        migrations.AlterField(
            model_name='group_room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.techerregist'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='chat.group_room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_app.techerregist')),
            ],
        ),
    ]
