# Generated by Django 6.0.2 on 2026-03-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_group_room_admin_student_and_more'),
        ('student_app', '0002_remove_student_department_studentassignmentattempt_and_more'),
        ('teacher_app', '0007_assignment_total_marks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_student_in_group'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'teacher'), name='unique_teacher_in_group'),
        ),
    ]
