# Generated by Django 6.0.2 on 2026-03-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_webhookevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
    ]
