# Generated by Django 6.0.2 on 2026-03-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_payroll_unique_together'),
        ('teacher_app', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'paid leave'), ('LWP', 'Leave Without Pay')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.payroll'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('teacher', 'period_start', 'period_end')},
        ),
    ]
