# Generated by Django 6.0.2 on 2026-03-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_alter_leave_leave_type_alter_payment_payroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
