# Generated by Django 6.0.2 on 2026-03-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_alter_payroll_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(default='unknown', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
